### ISSUE TITLE
close when I put the file

### ISSUE THREAD

**Issue by Darknight1616** [ClayAmore/ER-Save-Editor#88]
I decrypted a ps4 elden ring file with a discord bot from the server Xcier or protobuffer and I tried to put it into the save editor but the application just close when I put it.
Can you help me

**Comment by lsevero** [comment]
same, built it on linux to get the stacktraces:
```
# RUST_BACKTRACE=full ./er-save-editor

(er-save-editor:16032): dconf-WARNING **: 00:24:55.054: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=71f296babb789431e83c97b46189fa42 --binary-syntax --close-stderr”: Child process exited with code 1
thread 'main' panicked at src/main.rs:80:44:
Failed to read save: Custom { kind: UnexpectedEof, error: "failed to read 4 bytes from offset 28967885" }
stack backtrace:
   0:     0x560bdea5eeeb - std::backtrace_rs::backtrace::libunwind::trace::h3926e05c1d1f3b6d
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x560bdea5eeeb - std::backtrace_rs::backtrace::trace_unsynchronized::h9f5691494ac25ae6
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560bdea5eeeb - std::sys_common::backtrace::_print_fmt::h7e6bb7b81bf214f4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560bdea5eeeb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf688c88e28c91b4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560bdeaa30a0 - core::fmt::rt::Argument::fmt::h59a542682908b618
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:142:9
   5:     0x560bdeaa30a0 - core::fmt::write::hce91e70849a27dee
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1120:17
   6:     0x560bdea52f3d - std::io::Write::write_fmt::h0bba58d3b1b495e9
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/io/mod.rs:1762:15
   7:     0x560bdea5ecd4 - std::sys_common::backtrace::_print::hf3a4f110a22f16df
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x560bdea5ecd4 - std::sys_common::backtrace::print::h0450d1fd5fc83f73
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x560bdea878da - std::panicking::default_hook::{{closure}}::hee7ec73fab21a529
  10:     0x560bdea8757d - std::panicking::default_hook::he65be6b11b67d1e4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:292:9
  11:     0x560bdea87cf8 - std::panicking::rust_panic_with_hook::h9e4f07a5a69c9caf
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:779:13
  12:     0x560bdea5f2ce - std::panicking::begin_panic_handler::{{closure}}::h69a9732dd2e7007d
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:657:13
  13:     0x560bdea5f106 - std::sys_common::backtrace::__rust_end_short_backtrace::hf159dc40d4738bc4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x560bdea87a22 - rust_begin_unwind
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
  15:     0x560bdd2ce305 - core::panicking::panic_fmt::hf38ef33e65607e17
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
  16:     0x560bdd2ceba3 - core::result::unwrap_failed::h93afb55b612add5a
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/result.rs:1653:5
  17:     0x560bdd429481 - core::result::Result<T,E>::expect::h741f742b0dcbb14f
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/result.rs:1034:23
  18:     0x560bdd5d4ca0 - er_save_editor::App::open::hf80f625d222ce015
                               at /home/severo/ER-Save-Editor/src/main.rs:80:21
  19:     0x560bdd54f9a9 - <er_save_editor::App as eframe::epi::App>::update::{{closure}}::{{closure}}::{{closure}}::h0a0f9c0aa2c2aebf
                               at /home/severo/ER-Save-Editor/src/main.rs:127:43
  20:     0x560bdd47441b - core::ops::function::FnOnce::call_once{{vtable.shim}}::h19eb78c33d17819c
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  21:     0x560bde7995a0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h25c3a1ecf92dfbb9
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/alloc/src/boxed.rs:2007:9
  22:     0x560bde849865 - egui::ui::Ui::with_layout_dyn::h1722555c6c90a664
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/ui.rs:2020:21
  23:     0x560bdd4143b2 - egui::ui::Ui::with_layout::hc3d2ad3bfe39259a
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/ui.rs:2011:9
  24:     0x560bdd54f516 - <er_save_editor::App as eframe::epi::App>::update::{{closure}}::{{closure}}::h285a6cca33285c84
                               at /home/severo/ER-Save-Editor/src/main.rs:123:17
  25:     0x560bdd474313 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1355df812d8be84e
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  26:     0x560bdd4ffe6c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha332a54cfc393739
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/alloc/src/boxed.rs:2007:9
  27:     0x560bdd4131a0 - egui::ui::Ui::columns_dyn::h5bce5d85d79e33b6
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/ui.rs:2109:22
  28:     0x560bdd41ad68 - egui::ui::Ui::columns::h51b8938ae9149550
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/ui.rs:2081:9
  29:     0x560bdd54f414 - <er_save_editor::App as eframe::epi::App>::update::{{closure}}::hcefbe9a5d2ccd37c
                               at /home/severo/ER-Save-Editor/src/main.rs:122:13
  30:     0x560bdd47524b - core::ops::function::FnOnce::call_once{{vtable.shim}}::h70382a0821f7454e
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  31:     0x560bde7995a0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h25c3a1ecf92dfbb9
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/alloc/src/boxed.rs:2007:9
  32:     0x560bdd3271d5 - egui::containers::panel::TopBottomPanel::show_inside_dyn::{{closure}}::h5ee10160b262ce9f
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/panel.rs:747:13
  33:     0x560bdd4761d8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcaa9e274f0827af8
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  34:     0x560bde7995a0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h25c3a1ecf92dfbb9
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/alloc/src/boxed.rs:2007:9
  35:     0x560bde80345a - egui::containers::frame::Frame::show_dyn::h69807f6b55b142bb
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/frame.rs:270:19
  36:     0x560bdd46bb0a - egui::containers::frame::Frame::show::h68d5768eda2d8567
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/frame.rs:261:9
  37:     0x560bdd326ba8 - egui::containers::panel::TopBottomPanel::show_inside_dyn::h80aa6c83e3e04254
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/panel.rs:744:30
  38:     0x560bdd327770 - egui::containers::panel::TopBottomPanel::show_dyn::ha8311e3200acdc09
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/panel.rs:812:30
  39:     0x560bdd3275f0 - egui::containers::panel::TopBottomPanel::show::he9f761dd47d37b16
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/containers/panel.rs:796:9
  40:     0x560bdd5d53d1 - <er_save_editor::App as eframe::epi::App>::update::h756de5bc28659156
                               at /home/severo/ER-Save-Editor/src/main.rs:121:9
  41:     0x560bdda4dc37 - eframe::native::epi_integration::EpiIntegration::update::{{closure}}::ha6fcb71eb51f359b
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/epi_integration.rs:284:17
  42:     0x560bdda4f434 - egui::context::Context::run::h17ce6b6729a3abd4
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.26.2/src/context.rs:753:9
  43:     0x560bdda4d819 - eframe::native::epi_integration::EpiIntegration::update::h8ee178c42b55edac
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/epi_integration.rs:277:27
  44:     0x560bdd9ec1d7 - eframe::native::glow_integration::GlowWinitRunning::run_ui_and_paint::h487356c913c9283f
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/glow_integration.rs:578:13
  45:     0x560bdd9ea80d - <eframe::native::glow_integration::GlowWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint::h0d09d8996059ff8c
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/glow_integration.rs:402:13
  46:     0x560bdd9e3625 - eframe::native::run::run_and_return::{{closure}}::hcedafcfb22e5d950
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:99:17
  47:     0x560bdd9d853f - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h2a76cf2d497cdd30
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:294:13
  48:     0x560bdd9d85a0 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h33378d197d489cd0
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:294:13
  49:     0x560bdda27e82 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration::h00c3645dfd56ac4f
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:504:17
  50:     0x560bdda2f695 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout::h37e1542392a1a6e4
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:323:9
  51:     0x560bdda2674d - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::h5c1ff79cf88b79c8
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:237:13
  52:     0x560bdda27089 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand::he80fd4e6dbe6ad11
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/wayland/event_loop/mod.rs:201:19
  53:     0x560bdd9d2825 - winit::platform_impl::platform::EventLoop<T>::run_on_demand::h97196f81ab3aadf7
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs:821:56
  54:     0x560bdd9f6d4b - <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand::h8b8082b338cd14bf
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform/run_on_demand.rs:80:9
  55:     0x560bdd9e2e52 - eframe::native::run::run_and_return::h19a9b3328338096e
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:76:5
  56:     0x560bdd9e74ea - eframe::native::run::run_glow::{{closure}}::hed84714512fa6e89
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:400:13
  57:     0x560bdd9e2aaa - eframe::native::run::with_event_loop::{{closure}}::h32a39fc1b84ee677
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:58:12
  58:     0x560bdda19e49 - std::thread::local::LocalKey<T>::try_with::h3e530deee0310d39
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/thread/local.rs:270:16
  59:     0x560bdda194b4 - std::thread::local::LocalKey<T>::with::h2790dfae1dbc7372
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/thread/local.rs:246:9
  60:     0x560bdd9e28b6 - eframe::native::run::with_event_loop::hb19dd87981527e5b
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:48:5
  61:     0x560bdd9e70cf - eframe::native::run::run_glow::h8fc4cca48845512b
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/native/run.rs:398:16
  62:     0x560bdda4e185 - eframe::run_native::he396ba03e1b3a1b8
                               at /home/severo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.26.2/src/lib.rs:262:13
  63:     0x560bdd5d4929 - er_save_editor::main::h404f89391a5b75af
                               at /home/severo/ER-Save-Editor/src/main.rs:44:5
  64:     0x560bdd478642 - core::ops::function::FnOnce::call_once::ha1d62da6158a45fd
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:250:5
  65:     0x560bdd2e83a5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h912d8b7b818ec5d4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:154:18
  66:     0x560bdd52e6b6 - std::rt::lang_start::{{closure}}::h7d32df301be2f112
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:167:18
  67:     0x560bdea87914 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h79a1db7ef67e1194
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:284:13
  68:     0x560bdea87914 - std::panicking::try::do_call::h4d3f550f9f5d649e
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:552:40
  69:     0x560bdea87914 - std::panicking::try::h01b4e15c9906c472
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:516:19
  70:     0x560bdea87914 - std::panic::catch_unwind::h8f18404de61a31a9
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  71:     0x560bdea87914 - std::rt::lang_start_internal::{{closure}}::h9b2491841fb26cd6
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:48
  72:     0x560bdea87914 - std::panicking::try::do_call::ha5fc70c953975daf
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:552:40
  73:     0x560bdea87914 - std::panicking::try::hf2c81cc356fa2f99
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:516:19
  74:     0x560bdea6e87b - std::panic::catch_unwind::h6741cb988acde652
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  75:     0x560bdea6e87b - std::rt::lang_start_internal::h65f0529f246fb3ed
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:20
  76:     0x560bdd52e68a - std::rt::lang_start::he341d093748de4f2
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:166:17
  77:     0x560bdd5d5b1e - main
  78:     0x7faa0aa7a083 - __libc_start_main
  79:     0x560bdd2ced2e - _start
  80:                0x0 - <unknown>

```

**Comment by izaac** [comment]
https://github.com/ClayAmore/ER-Save-Editor/issues/43

**Comment by difesousa** [comment]
estou com um problema, save de ps4 e uso o save wizard para decompactar, mas quando abro o arquivo o editor fecha automaticamente, alguém sabe como resolver?
